config/routes.rb
Rails.application.routes.draw do
  resources :exercise_programs
  resources :exercise_types
  resources :general_stats
  resources :weight_sets
  resources :exercise_sessions
  devise_for :users
  root 'exercise_sessions#index'#we'll make this a landing page later
  resources :exercise_sessions, only: [:index, :show]
  resources :general_stats, only: [:index, :show]
  resources :weight_sets, only: [:index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/weightSet.rb
class WeightSet < ApplicationRecord
  def self.weightSet
    where(id:1, weight: 185, reps: 7, visit_id: 1)
  end
end

app/models/weight_set.rb
class WeightSet < ApplicationRecord
  belongs_to :exercise_session
  has_one :user, through: :exercise_session
  has_one :exercise_type, through: :exercise_session

  validates :weight, :numericality => { :greater_than_or_equal_to => 0 }
  validates :reps, :numericality => { :greater_than_or_equal_to => 0 }

  def self.for_page(page, current_user, page_limit=10)
   joins(:exercise_session)
    .where('exercise_sessions.user_id = ?', current_user.id)
    .limit(page_limit)
    .offset(page.to_i * page_limit)
  end

end

app/controllers/weightSetController.rb
class WeightSetController < ApplicationController
  def index
    @weightSets = WeightSet.all
  end

  def show
    @weightSets = WeightSet.find(params[:id])
    respond_to do |format|
      format.json {render json: @weightSet}
    end
  end
end

app/controllers/weight_sets_controller.rb
class WeightSetsController < ApplicationController
  before_action :set_weight_set, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :set_page, only: [:index]
  # GET /weight_sets
  # GET /weight_sets.json
  def index
    @weight_sets = WeightSet
    .for_page(@page, current_user)

    # = WeightSet.includes(:exercise_type)
    #  .joins(:exercise_session)
    #  .where('exercise_sessions.user_id = ?', current_user.id).limit(10).offset(@page.to_i * 10)



    #don't do this, this is silly
#     @exercise_sessions = ExerciseSession.where(user: current_user)
#     @weight_sets = []
#     @exercise_sessions.each do |exercise_session|
# #      for each weoghtgset in exercise_session.weight_sets {\
# #        @weight_sets.push(weoghtgset.this)
# #      }
#         @weight_sets.push(exercise_session.weight_sets)
#     end
#     @weight_sets.flatten!
#     #binding.pry
  end


  #SELECT weight_set FROM weight_sets WHERE weight_ == current_user.id)

  # GET /weight_sets/1
  # GET /weight_sets/1.json
  def show
  end

  # GET /weight_sets/new
  def new
    @weight_set = WeightSet.new
  end

  # GET /weight_sets/1/edit
  def edit
  end

  # POST /weight_sets
  # POST /weight_sets.json
  def create
#    binding.pry
    @weight_set = WeightSet.new(weight_set_params)

    respond_to do |format|
      if @weight_set.save
        format.html { redirect_to @weight_set, notice: 'Weight set was successfully created.' }
        format.json { render :show, status: :created, location: @weight_set }
      else
        format.html { render :new }
        format.json { render json: @weight_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weight_sets/1weight_sets
  # PATCH/PUT /weight_sets/1.json
  def update
    respond_to do |format|
      if @weight_set.update(weight_set_params)
        format.html { redirect_to @weight_set, notice: 'Weight set was successfully updated.' }
        format.json { render :show, status: :ok, location: @weight_set }
      else
        format.html { render :edit }
        format.json { render json: @weight_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weight_sets/1
  # DELETE /weight_sets/1.json
  def destroy
    @weight_set.destroy
    respond_to do |format|
      format.html { redirect_to weight_sets_url, notice: 'Weight set was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weight_set
      @weight_set = WeightSet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def weight_set_params
      params.require(:weight_set).permit(:weight, :reps, :exercise_session_id)
    end#HAHAHAHAHAHA

    def set_page
      @page = params[:page] || 0
    end
end

app/helpers/weight_sets_helper.rb
module WeightSetsHelper
end

app/views/weight_sets/_form.html.erb
<%= form_with(model: weight_set, local: true) do |form| %>
  <% if weight_set.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(weight_set.errors.count, "error") %> prohibited this weight_set from being saved:</h2>

      <ul>
      <% weight_set.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :weight %>
    <%= form.text_field :weight, id: :weight_set_weight %>
  </div>

  <div class="field">
    <%= form.label :reps %>
    <%= form.text_field :reps, id: :weight_set_reps %>
  </div>

  <div class="field">
    <%= form.label :exercise_session %>

      <%= form.collection_select(:exercise_session_id, current_user.exercise_sessions, :id, :date, prompt: true) %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/weight_sets/edit.html.erb
<h1>Editing Weight Set</h1>

<%= render 'form', weight_set: @weight_set %>

<%= link_to 'Show', @weight_set %> |
<%= link_to 'Back', weight_sets_path %>

app/views/weight_sets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Weight Sets</h1>

<%= link_to 'New Weight Set', new_weight_set_path %>
<br>
<%= link_to 'First', weight_sets_path(page: 0) %>
<%= link_to 'Previous', weight_sets_path(page: @page.to_i - 1) %>
<%= link_to 'Next', weight_sets_path(page: @page.to_i + 1) %>
<%= link_to 'Last', weight_sets_path(page: ((WeightSet.all.size)/10)) %>

<br>

<table>
  <thead>
    <tr>
      <th>Weight</th>
      <th>Reps</th>
      <th><%= link_to 'Exercise session', exercise_sessions_path(page: 0) %></th>
      <th>Date</th>
      <th>Exercise type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @weight_sets.each do |weight_set| %>
      <tr>
        <td><%= weight_set.weight %></td>
        <td><%= weight_set.reps %></td>
        <td><%= link_to weight_set.exercise_session_id, exercise_session_path(weight_set.exercise_session_id) %></td>
        <td><%= display_date(weight_set.exercise_session) %></td>
        <td><%= weight_set.exercise_type.name || 'None'  %></td>
        <td><%= link_to 'Show', weight_set %></td>
        <td><%= link_to 'Edit', edit_weight_set_path(weight_set) %></td>
        <td><%= link_to 'Destroy', weight_set, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>

</table>

app/views/weight_sets/new.html.erb
<h1>New Weight Set</h1>

<%= render 'form', weight_set: @weight_set %>

<%= link_to 'Back', weight_sets_path %>

app/views/weight_sets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Weight:</strong>
  <%= @weight_set.weight %>
</p>

<p>
  <strong>Reps:</strong>
  <%= @weight_set.reps %>
</p>

<p>
  <strong>Exercise session:</strong>
  <%= @weight_set.exercise_session %>
</p>


<%= link_to 'Edit', edit_weight_set_path(@weight_set) %> |
<%= link_to 'Back', weight_sets_path %>