config/routes.rb
Rails.application.routes.draw do
  resources :exercise_programs
  resources :exercise_types
  resources :general_stats
  resources :weight_sets
  resources :exercise_sessions
  devise_for :users
  root 'exercise_sessions#index'#we'll make this a landing page later
  resources :exercise_sessions, only: [:index, :show]
  resources :general_stats, only: [:index, :show]
  resources :weight_sets, only: [:index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/exercise_types_controller.rb
class ExerciseTypesController < ApplicationController
  before_action :set_exercise_type, only: [:show, :edit, :update, :destroy]
  before_action :set_page, only: [:index]

  # GET /exercise_types
  # GET /exercise_types.json
  def index
#    @exercise_types = ExerciseType.where('exercise_types.user_id = ?', current_user.id).limit(10).offset(@page.to_i * 10)
    @exercise_types = ExerciseType
    .for_page(@page, current_user)
  end

  # GET /exercise_types/1
  # GET /exercise_types/1.json
  def show
  end

  # GET /exercise_types/new
  def new
    @exercise_type = ExerciseType.new
  end

  # GET /exercise_types/1/edit
  def edit
  end

  # POST /exercise_types
  # POST /exercise_types.json
  def create
    @exercise_type = ExerciseType.new(exercise_type_params)
    @exercise_type.user_id = current_user.id

    respond_to do |format|
      if @exercise_type.save
        format.html { redirect_to @exercise_type, notice: 'Exercise type was successfully created.' }
        format.json { render :show, status: :created, location: @exercise_type }
      else
        format.html { render :new }
        format.json { render json: @exercise_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exercise_types/1
  # PATCH/PUT /exercise_types/1.json
  def update
    respond_to do |format|
      if @exercise_type.update(exercise_type_params)
        format.html { redirect_to @exercise_type, notice: 'Exercise type was successfully updated.' }
        format.json { render :show, status: :ok, location: @exercise_type }
      else
        format.html { render :edit }
        format.json { render json: @exercise_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercise_types/1
  # DELETE /exercise_types/1.json
  def destroy
    @exercise_type.destroy
    respond_to do |format|
      format.html { redirect_to exercise_types_url, notice: 'Exercise type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exercise_type
      @exercise_type = ExerciseType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exercise_type_params
      params.require(:exercise_type).permit(:name, :description, :user_id)
    end

    def set_page
      @page = params[:page] || 0
    end


end

app/helpers/exercise_types_helper.rb
module ExerciseTypesHelper
end

app/views/exercise_types/_form.html.erb
<%= form_with(model: exercise_type, local: true) do |form| %>
  <% if exercise_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(exercise_type.errors.count, "error") %> prohibited this exercise_type from being saved:</h2>

      <ul>
      <% exercise_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :exercise_type_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :exercise_type_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/exercise_types/edit.html.erb
<h1>Editing Exercise Type</h1>

<%= render 'form', exercise_type: @exercise_type %>

<%= link_to 'Show', @exercise_type %> |
<%= link_to 'Back', exercise_types_path %>

app/views/exercise_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Exercise Types</h1>

<%= link_to 'New Exercise Type', new_exercise_type_path %>
<br>
<%= link_to 'First', exercise_types_path(page: 0) %>
<%= link_to 'Previous', exercise_types_path(page: @page.to_i - 1) %>
<%= link_to 'Next', exercise_types_path(page: @page.to_i + 1) %>
<%= link_to 'Last', exercise_types_path(page: ((ExerciseType.all.size)/10)) %>


<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exercise_types.each do |exercise_type| %>
      <tr>
        <td><%= exercise_type.name %></td>
        <td><%= exercise_type.description %></td>
        <td><%= link_to 'Show', exercise_type %></td>
        <td><%= link_to 'Edit', edit_exercise_type_path(exercise_type) %></td>
        <td><%= link_to 'Destroy', exercise_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/exercise_types/new.html.erb
<h1>New Exercise Type</h1>

<%= render 'form', exercise_type: @exercise_type %>

<%= link_to 'Back', exercise_types_path %>

app/views/exercise_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @exercise_type.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @exercise_type.description %>
</p>

<%= link_to 'Edit', edit_exercise_type_path(@exercise_type) %> |
<%= link_to 'Back', exercise_types_path %>