config/routes.rb
Rails.application.routes.draw do
  resources :exercise_programs
  resources :exercise_types
  resources :general_stats
  resources :weight_sets
  resources :exercise_sessions
  devise_for :users
  root 'exercise_sessions#index'#we'll make this a landing page later
  resources :exercise_sessions, only: [:index, :show]
  resources :general_stats, only: [:index, :show]
  resources :weight_sets, only: [:index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/exercise_session.rb
class ExerciseSession < ApplicationRecord
  belongs_to :user
  belongs_to :exercise_type
  belongs_to :exercise_program
  has_many :weight_sets



end

app/controllers/exerciseSessionController.rb
class ExerciseSessionController < ApplicationController
  def index
    @exerciseSessions = ExerciseSession.all
  end

  def show
    @exerciseSessions = ExerciseSession.find(params[:id])
    respond_to do |format|
      format.json {render json: @exerciseSession}
    end
  end
end

app/controllers/exercise_sessions_controller.rb
class ExerciseSessionsController < ApplicationController
  before_action :set_exercise_session, only: [:show, :edit, :update, :destroy]
  before_action :set_page, only: [:index]
#make sure this works if nobody is logged in
  before_action :authenticate_user!

  # GET /exercise_sessions
  # GET /exercise_sessions.json
  def index

#    @exercise_sessions = ExerciseSession
#      .where('exercise_sessions.user_id = ?', current_user.id).limit(10).offset(@page.to_i * 10)
    #type and session were included/joined for weight_set to eliminate/prevent cache calls for  'session and user'
    #now we are trying to eager load to eliminate/prevent cache calls for 'exercise type and program'

#    @exercise_sessions = ExerciseSession
#    .includes(:exercise_type)
#      .joins(:exercise_program)
#      .where('exercise_programs.user_id = ?', current_user.id).limit(10).offset(@page.to_i * 10)
#okay cool but now we're still caching exercise program

#@exercise_sessions = ExerciseSession
#.includes(:exercise_type, :exercise_program)
#  .joins(:exercise_type)
#  .where('exercise_sessions.user_id = ?', current_user.id).limit(10).offset(@page.to_i * 10)
#even better

@exercise_sessions = ExerciseSession
.for_page(@page, current_user)
#EVEN BETTER

#@exercise_sessions = ExerciseSession
#.includes(:exercise_type, :exercise_program)
#  .joins(:exercise_program)
#  .where('exercise_programs.user_id = ?', current_user.id).limit(10).offset(@page.to_i * 10)
#this also works
#exercise_programs OR type works



  end

  # GET /exercise_sessions/1
  # GET /exercise_sessions/1.json
  def show
    #binding.pry
  end

  # GET /exercise_sessions/new
  def new
    @exercise_session = ExerciseSession.new
  end

  # GET /exercise_sessions/1/edit
  def edit
  end

  # POST /exercise_sessions
  # POST /exercise_sessions.json
  def create
    @exercise_session = ExerciseSession.new(exercise_session_params)
    @exercise_session.user_id = current_user.id

    #binding.pry


    respond_to do |format|
      if @exercise_session.save
        format.html { redirect_to @exercise_session, notice: 'Exercise session was successfully created.' }
        format.json { render :show, status: :created, location: @exercise_session }
      else
        format.html { render :new }
        format.json { render json: @exercise_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exercise_sessions/1
  # PATCH/PUT /exercise_sessions/1.json
  def update
    respond_to do |format|
      if @exercise_session.update(exercise_session_params)
        format.html { redirect_to @exercise_session, notice: 'Exercise session was successfully updated.' }
        format.json { render :show, status: :ok, location: @exercise_session }
      else
        format.html { render :edit }
        format.json { render json: @exercise_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercise_sessions/1
  # DELETE /exercise_sessions/1.json
  def destroy
    @exercise_session.destroy
    respond_to do |format|
      format.html { redirect_to exercise_sessions_url, notice: 'Exercise session was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exercise_session
      @exercise_session = ExerciseSession.find(params[:id])
      #      @exercise_session = ExerciseSession.find(params[:id], :limit => 25)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exercise_session_params
      params.require(:exercise_session).permit(:date, :user_id, :exercise_type_id, :exercise_program_id)
    end

    def set_page
      @page = params[:page] || 0
    end

end

app/helpers/exercise_sessions_helper.rb
module ExerciseSessionsHelper
end

app/views/exercise_sessions/_form.html.erb
<%= form_with(model: exercise_session, local: true) do |form| %>
  <% if exercise_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(exercise_session.errors.count, "error") %> prohibited this exercise_session from being saved:</h2>

      <ul>
      <% exercise_session.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_field :date, id: :exercise_session_date %>
  </div>

  <div class="field">
    <%= form.label :exercise_type %>
      <%= form.collection_select(:exercise_type_id, current_user.exercise_types, :id, :name, prompt: true) %>
  </div>

  <div class="field">
    <%= form.label :exercise_program %>
      <%= form.collection_select(:exercise_program_id, current_user.exercise_programs, :id, :name, prompt: true) %>
  </div>

<!--
  <div class="field">
    <%= form.label :type_name %>
    <%= form.text_field :type_name, id: :exercise_session_type_name %>
  </div>

  <div class="field">
    <%= form.label :program %>
    <%= form.text_field :program, id: :exercise_session_program %>
  </div>
-->


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/exercise_sessions/edit.html.erb
<h1>Editing Exercise Session</h1>

<%= render 'form', exercise_session: @exercise_session %>

<%= link_to 'Show', @exercise_session %> |
<%= link_to 'Back', exercise_sessions_path %>

app/views/exercise_sessions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Exercise Sessions</h1>

<%= link_to 'New Exercise Session', new_exercise_session_path %>
<br>
<%= link_to 'First', exercise_sessions_path(page: 0) %>
<%= link_to 'Previous', exercise_sessions_path(page: @page.to_i - 1) %>
<%= link_to 'Next', exercise_sessions_path(page: @page.to_i + 1) %>
<%= link_to 'Last', exercise_sessions_path(page: ((ExerciseSession.all.size)/10)) %>


<br>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th><%= link_to 'Type name', exercise_types_path(page: 0) %></th>
      <th>Program</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exercise_sessions.each do |exercise_session| %>
      <tr>
        <td><%= display_date(exercise_session) %></td>
        <td><%= exercise_session.exercise_type.try(:name) || 'None' %></td>
        <td><%= exercise_session.exercise_program.name %></td>
        <td><%= link_to 'Show', exercise_session %></td>
        <td><%= link_to 'Edit', edit_exercise_session_path(exercise_session) %></td>
        <td><%= link_to 'Destroy', exercise_session, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/exercise_sessions/new.html.erb
<h1>New Exercise Session</h1>

<%= render 'form', exercise_session: @exercise_session %>

<%= link_to 'Back', exercise_sessions_path %>

app/views/exercise_sessions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= display_date(@exercise_session) %>
</p>

<p>
  <strong>Type name:</strong>
  <%= @exercise_session.exercise_type.name %>
</p>

<p>
  <strong>Program:</strong>
  <%= @exercise_session.exercise_program.name %>
</p>



<%= link_to 'Edit', edit_exercise_session_path(@exercise_session) %> |
<%= link_to 'Back', exercise_sessions_path %>