config/routes.rb
Rails.application.routes.draw do
  resources :exercise_programs
  resources :exercise_types
  resources :general_stats
  resources :weight_sets
  resources :exercise_sessions
  devise_for :users
  root 'exercise_sessions#index'#we'll make this a landing page later
  resources :exercise_sessions, only: [:index, :show]
  resources :general_stats, only: [:index, :show]
  resources :weight_sets, only: [:index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--
This is on every page
-->
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
    <%= javascript_pack_tag 'hello_react' %>


  </head>

  <body>

    <div>
     <ul>
       <% if current_user %>
         <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
         <!-- THIS IS BETTER THAN A <a href="blargh" /> -->
         <!-- link_to(text, url, options) we can add a third 'options' param/> -->
       <% else %>
         <li><%= link_to "Sign Up", new_user_registration_path %></li>
         <% #link_to("Sign up", "users/sign_up/"), this is how we'd do it without a method hahaha
      # = <-- this equal will cause problems because it will try to render whatever's inside,
      # and if it's a comment, nothing happens LOL
       %>
         <li><%= link_to "Sign In", new_user_session_path %></li>
       <% end %>
     </ul>
      <!-- for Ken: this is supposed to be part of something on every page:
it'll allow anyone to readily switch to the 'general stats', 'exercise sessions' and 'weight sets' links-->
      <br>
       <ul>
         <!-- link_to(text, url, options) we can add a third 'options' param/> -->
         <li><%= link_to "General Stats", general_stats_path %></li>
         <li><%= link_to "Exercise Sessions", exercise_sessions_path %></li>
         <li><%= link_to "Weight Sets", weight_sets_path %></li>
         <li><%= link_to "Exercise Types", exercise_types_path %></li>
         <li><%= link_to "Exercise Programs", exercise_programs_path %></li>
      </ul>
<!-- end possibly broken/buggy code-->
   </div>


    <%= yield %>
    <!--
yield gets replaced with whatever *.erb file the router is currently 'pointing' to/at   -->
<%= javascript_pack_tag 'application' %>

  </body>
</html>